default_settings: &default_settings
  normalize: true
  n_envs: 1
  policy: 'MlpPolicy'
  n_timesteps: !!float 1e6
  batch_size: 1_000
  n_steps: 1_000
  gamma: 0.98
  learning_rate: 0.0003
  n_epochs: 100
  # net_arch: null # Use default architecture net_arch=dict(pi=[64, 64], vf=[64, 64])

Ant-v5: 
  <<: *default_settings

HalfCheetah-v5:
  <<: *default_settings

Hopper-v5:
  <<: *default_settings

Swimmer-v5:
  <<: *default_settings

InvertedPendulum-v5:
  <<: *default_settings

InvertedDoublePendulum-v5:
  <<: *default_settings



# V-4
Ant-v4: 
  <<: *default_settings

HalfCheetah-v4:
  <<: *default_settings

Hopper-v4:
  <<: *default_settings

Swimmer-v4:
  <<: *default_settings

InvertedPendulum-v4:
  <<: *default_settings

InvertedDoublePendulum-v4:
  <<: *default_settings 